# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Mod Properties
mod_version=1.0.0
maven_group=technicfan.smallqolthings
archives_base_name=smallqolthings

# Dependencies
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
